{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "thehubpub.fullname" . }}
spec:
  hosts:
  - "{{ include "thehubpub.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
  - "{{ include "thehubpub.fullname" . }}.{{ .Values.regionCode }}.{{ .Release.Namespace }}.aws.beantownpub.com"
  - "demo.{{ .Release.Namespace }}.thehubpub.com"
  - "thehubpub.com"
  - "www.thehubpub.com"

  gateways:
  - istio-system/web-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.containerPort }}
        host: "{{ include "thehubpub.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        subset: {{ include "thehubpub.fullname" . }}
      headers:
        response:
          remove:
          - "x-envoy-upstream-service-time"
          - "x-powered-by"
{{- end }}
